$(function(){
	//全选;
	var flag=false;
	$(".allcheck").on("click",function(){
		if(this.checked){
			$(".check[type='checkbox']").each(function(){
				this.checked=true;
				flag=true;
			});
		}else{
			$(".check[type='checkbox']").each(function(){
				this.checked=false;
				flag=false;
			});
		}
	});
	//关闭订单
	$(".sure-close").click(function(){
		$(".check[type='checkbox']").each(function(){
			if(this.checked==true){
				flag=true;
				$(".modal-abnormal").show();

			}
		});
		if(flag){
			$(".modal-abnormal").show();
		}else{
			$(".modal-abnormal1").show();
		}
	});
	//恢复正常
	$(".recover-normal").click(function(){
		$(".check[type='checkbox']").each(function(){
			if(this.checked==true){
				flag=true;
				$(".modal-abnormal2").show();

			}
		});
		if(flag){
			$(".modal-abnormal2").show();
		}else{
			$(".modal-abnormal1").show();
		}
	});
	//修改异常;
	$(".change-statu").click(function(){
		$(".check[type='checkbox']").each(function(){
			if(this.checked==true){
				flag=true;
				$(".modal-abnormal3").show();
			}
		});
		if(flag){
			$(".modal-abnormal3").show();
		}else{
			$(".modal-abnormal1").show();
		}
	});
	$(".change-bei").click(function(){
		$(".check[type='checkbox']").each(function(){
			if(this.checked==true){
				flag=true;
				$(".modal-abnormal4").show();

			}
		});
		if(flag){
			$(".modal-abnormal4").show();
		}else{
			$(".modal-abnormal1").show();
		}
	});
	//判断是否覆盖
	$(".abnormal4-sure").click(function(){
		if($(".change-method").val()=="在原备注上追加"){
			$(".check[type='checkbox']:checked").each(function(){
				$(this).parents("tr").find('td:nth-child(5)').html($(this).parents("tr").find('td:nth-child(5)').html()+"[追加]"+$(".abnormal4-mark").val());
			    $(".modal-abnormal4").hide();
			});
		}else if($(".change-method").val()=="覆盖原先的备注"){
			$(".check[type='checkbox']:checked").each(function(){
				$(this).parents("tr").find('td:nth-child(5)').html($(".abnormal4-mark").val());
			    $(".modal-abnormal4").hide();
			});
		}
	});
})